apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: krishnasravi/notification-service:v1.1
        ports:
        - containerPort: 8082
#        resources:
#          requests:
#            cpu: "100m"
#            memory: "256Mi"
#          limits:
#            cpu: "500m"
#            memory: "512Mi"
